discount:
  assemblyscript:
    package: "@shopify/extension-point-as-discount"
    version: "^0.0.13"
    sdk-version: "^1.2.3"
unit-limit-per-order:
  assemblyscript:
    package: "@shopify/extension-point-as-unit-limit-per-order"
    version: "^0.0.13"
    sdk-version: "^1.2.3"

